config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "promotion" => "static_pages#promotion"
  get "info" => "static_pages#info"
  get "member" => "static_pages#member"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :edit, :update]
  resources :flights, only: [:index, :show]
  resources :tickets, only: [:index, :show]
  resources :carts, only: [:index]
  resources :tickets, only: [:index, :update]
  resources :cart_infos, only: [:create]
  resources :schedules, only: :index
  resources :buy_tickets, only: [:index, :create]
  resources :buy_many_tickets, only: [:index, :create]
  resources :swap_tickets, only: [:index, :update]

  namespace :admin do
    root "dashboards#index"
    resources :companies
    resources :flights
    resources :carts
    resources :places
    resources :planes
    resources :tickets
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :manage_flights, only: :update
    resources :manage_planes, only: :update
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :planes

  validates :name, presence: true, length: {maximum: 20}
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :require_admin
  before_action :load_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all.paginate page: params[:page], per_page: 10
  end

  def show
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new company_params
    if @company.save
      redirect_to [:admin, @company]
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @company.update_attributes company_params
      flash[:success] = "Sửa thành công"
      redirect_to [:admin, @company]
    else
      flash[:danger] = "Sửa thất bại"
      render "edit"
    end
  end

  def destroy
    if @company.destroy
      flash[:success] = "Xóa thành công"
      redirect_to admin_companys_path
    else
      flash[:danger] = "Xóa thất bại"
      redirect_to admin_companys_path
    end
  end

  private
  def company_params
    params.require(:company).permit :name
  end

  def load_company
    @company = Company.find params[:id]
  end
end

app/views/admin/companies/edit.html.slim
#form-box
  h2 = t "admin.company.edit_company"
  hr
  = form_for [:admin, @company] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :name
      .col-xs-6
        = f.text_field :name, class: "form-control"
    
    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.edit"), class: "btn btn-primary btn-block"

app/views/admin/companies/index.html.slim
h2 = t "admin.company.index_company"

table.table.table-bordered.text-center
  tr
    td.info = t "admin.company.name"
    td.info = t "admin.company.select"

  - @companies.each do |company|
    tr
      td = company.name
      td
        = link_to t("button.show"), [:admin, company] , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.edit"), edit_admin_company_path(company) , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.delete"), [:admin, company], method: :delete,
          data: {confirm: t("button.you_sure")}, class: "btn btn-primary btn-xs"

h4 = link_to t("admin.company.new_company"), new_admin_company_path

= paginate @companies

app/views/admin/companies/new.html.slim
#form-box
  h2 = t "admin.company.new_company"
  hr
  = form_for [:admin, @company] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :name
      .col-xs-6
        = f.text_field :name, class: "form-control"
    
    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.create"), class: "btn btn-primary btn-block"

app/views/admin/companies/show.html.slim
h2 = t "admin.company.show_company"

= @company.name