config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "promotion" => "static_pages#promotion"
  get "info" => "static_pages#info"
  get "member" => "static_pages#member"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :edit, :update]
  resources :flights, only: [:index, :show]
  resources :tickets, only: [:index, :show]
  resources :carts, only: [:index]
  resources :tickets, only: [:index, :update]
  resources :cart_infos, only: [:create]
  resources :schedules, only: :index
  resources :buy_tickets, only: [:index, :create]
  resources :buy_many_tickets, only: [:index, :create]
  resources :swap_tickets, only: [:index, :update]

  namespace :admin do
    root "dashboards#index"
    resources :companies
    resources :flights
    resources :carts
    resources :places
    resources :planes
    resources :tickets
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :manage_flights, only: :update
    resources :manage_planes, only: :update
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :start_flights, class_name: Flight.name, dependent: :destroy, foreign_key: :start_place_id
  has_many :end_flights, class_name: Flight.name, dependent: :destroy, foreign_key: :end_place_id

  validates :city, presence: true, length: {maximum: 20}
  validates :country, presence: true, length: {maximum: 20}
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :require_admin
  before_action :load_place, only: [:show, :edit, :update, :destroy]

  def index
    @search = Place.search params[:q]
    @search.sorts = 'city asc' if @search.sorts.empty?
    @places = @search.result.paginate page: params[:page], per_page: 10
  end

  def show
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new place_params
    if @place.save
      flash[:success] = "Tạo thành công"
      redirect_to [:admin, @place]
    else
      flash[:danger] = "Tạo thất bại"
      render "new"
    end
  end

  def edit
  end

  def update
    if @place.update_attributes place_params
      flash[:success] = "Sửa thành công"
      redirect_to [:admin, @place]
    else
      flash[:danger] = "Sửa thất bại"
      render "edit"
    end
  end

  def destroy
    if @place.destroy
      flash[:success] = "Xóa thành công"
      redirect_to admin_places_path
    else
      flash[:danger] = "Xóa thất bại"
      redirect_to admin_places_path
    end
  end

  private
  def place_params
    params.require(:place).permit :city, :country
  end

  def load_place
    @place = Place.find params[:id]
  end
end

app/views/admin/places/edit.html.slim
#form-box
  h2 = t "admin.place.edit_place"
  hr
  = form_for [:admin, @place] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :city
      .col-xs-6
        = f.text_field :city, class: "form-control"

    .form-group.row
      .col-xs-6
        = f.label :country
      .col-xs-6
        = f.text_field :country, class: "form-control"

    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.edit"), class: "btn btn-primary btn-block"

app/views/admin/places/index.html.slim
h2 = t "admin.place.index_place"

table.table.table-bordered.text-center
  tr
    th.info.text-center = sort_link @search, :city, t("admin.place.city")
    th.info.text-center = sort_link @search, :country, t("admin.place.country")
    th.info.text-center = t "admin.place.select"

  - @places.each do |place|
    tr
      td = place.city
      td = place.country
      td
        = link_to t("button.show"), [:admin, place] , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.edit"), edit_admin_place_path(place) , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.delete"), [:admin, place], method: :delete,
          data: {confirm: t("button.you_sure")}, class: "btn btn-primary btn-xs"

h4 = link_to t("admin.place.new_place"), new_admin_place_path

= paginate @places

app/views/admin/places/new.html.slim
#form-box
  h2 = t "admin.place.new_place"
  hr
  = form_for [:admin, @place] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :city
      .col-xs-6
        = f.text_field :city, class: "form-control"

    .form-group.row
      .col-xs-6
        = f.label :country
      .col-xs-6
        = f.text_field :country, class: "form-control"

    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.create"), class: "btn btn-primary btn-block"

app/views/admin/places/show.html.slim
h2 = t "admin.place.show_place"

= @place.city
= @place.country