config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "promotion" => "static_pages#promotion"
  get "info" => "static_pages#info"
  get "member" => "static_pages#member"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :edit, :update]
  resources :flights, only: [:index, :show]
  resources :tickets, only: [:index, :show]
  resources :carts, only: [:index]
  resources :tickets, only: [:index, :update]
  resources :cart_infos, only: [:create]
  resources :schedules, only: :index
  resources :buy_tickets, only: [:index, :create]
  resources :buy_many_tickets, only: [:index, :create]
  resources :swap_tickets, only: [:index, :update]

  namespace :admin do
    root "dashboards#index"
    resources :companies
    resources :flights
    resources :carts
    resources :places
    resources :planes
    resources :tickets
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :manage_flights, only: :update
    resources :manage_planes, only: :update
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :plane
  belongs_to :flight
  belongs_to :user
  has_many :tickets

  after_update :assign_ticket

  def paypal_url(return_path)
    values = {
      :business => 'airline-app1@gmail.com',
      :cmd => '_cart',
      :upload => 1,
      :return => return_path,
      :invoice => id,
      :notify_url => "http://7dd97ee8.ngrok.com/cart_infos"
    }

    tickets.each_with_index do |ticket, index|
      values.merge!({
        "amount_#{index+1}" => ticket.price,
        "item_name_#{index+1}" => ticket.location,
        "item_number_#{index+1}" => ticket.id,
        "quantity_#{index+1}" => 1
      })
    end

    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  private
  def assign_ticket
    if status == "Completed"
      self.tickets.each do |ticket|
        ticket.update_attributes status: 2, user_id: user_id
      end
    end
  end
end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < ApplicationController
  before_action :require_admin
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = current_user.carts.order :id
  end
end

app/views/carts/index.html.slim
.row
  .col-xs-2#info_user
    = image_tag(current_user.image, height: "120px", width: "120px", class: "img-circle")
    h5.text-info
      - if current_user.general?
        | Hạng phổ thông
      - elsif current_user.special?
        | Hạng đặc biệt
      - elsif current_user.business?
        | Hạng doanh nhân
    h2 = current_user.name
  .col-xs-10#paycart
    - if @carts.count == 0
      h3.text-danger Chưa có hóa đơn nào
    - else
      h3.text-info style="padding-left:10px;" Hóa đơn của bạn
      - @carts.each do |cart|
        #paycart_item
          - if cart.status == "Completed"
            h4.text-success
              | Hóa đơn số 
              = cart.id
            - cart.tickets.each do |ticket|
              p
                strong Vị trí vé: 
                = ticket.location
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Giá vé: 
                = ticket.price
                | $&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Hạng vé: 
                - if ticket.type1?
                  | Hạng 1
                - elsif ticket.type2?
                  | Hạng 2
                - elsif ticket.type3?
                  | Hạng 3
                - elsif ticket.other?
                  | Hạng khác 
            h5.text-success style="text-align:right;" Đã thanh toán
          - else
            h4.text-danger
              | Hóa đơn số 
              = cart.id
            - cart.tickets.each do |ticket|
              p
                strong Vị trí vé: 
                = ticket.location
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Giá vé: 
                = ticket.price
                | $&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Hạng vé: 
                - if ticket.type1?
                  | Hạng 1
                - elsif ticket.type2?
                  | Hạng 2
                - elsif ticket.type3?
                  | Hạng 3
                - elsif ticket.other?
                  | Hạng khác
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Mã máy bay: 
                = ticket.plane.code
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Mã chuyến bay: 
                = ticket.flight.code
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                strong Mã vé: 
                = ticket.id
                | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                = link_to "Hủy vé", ticket_path(ticket), method: :patch, data: {confirm: "Bạn có chắc chắn hủy vé?"}
            h5 style="text-align:right;" = link_to "Thanh toán", cart.paypal_url(carts_url)