config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "promotion" => "static_pages#promotion"
  get "info" => "static_pages#info"
  get "member" => "static_pages#member"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :edit, :update]
  resources :flights, only: [:index, :show]
  resources :tickets, only: [:index, :show]
  resources :carts, only: [:index]
  resources :tickets, only: [:index, :update]
  resources :cart_infos, only: [:create]
  resources :schedules, only: :index
  resources :buy_tickets, only: [:index, :create]
  resources :buy_many_tickets, only: [:index, :create]
  resources :swap_tickets, only: [:index, :update]

  namespace :admin do
    root "dashboards#index"
    resources :companies
    resources :flights
    resources :carts
    resources :places
    resources :planes
    resources :tickets
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :manage_flights, only: :update
    resources :manage_planes, only: :update
  end
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  belongs_to :company
  has_many :flights
  has_many :tickets
  has_many :carts

  validates :code, presence: true, length: {maximum: 20}
  validates :name, presence: true, length: {maximum: 20}

  enum status: [:not_ready, :ready]
end

app/controllers/admin/planes_controller.rb
class Admin::PlanesController < ApplicationController
  before_action :require_admin
  before_action :load_plane, only: [:show, :edit, :update, :destroy]

  def index
    @search = Plane.search params[:q]
    @search.sorts = 'code asc' if @search.sorts.empty?
    @planes = @search.result.includes(:company).paginate page: params[:page], per_page: 10
  end

  def show
  end

  def new
    @plane = Plane.new
    @companies = Company.all
  end

  def create
    @plane = Plane.new plane_params
    if @plane.save
      flash[:success] = "Tạo thành công"
      redirect_to [:admin, @plane]
    else
      flash[:danger] = "Tạo thất bại"
      render "new"
    end
  end

  def edit
    @companies = Company.all
  end

  def update
    if @plane.update_attributes plane_params
      flash[:success] = "Sửa thành công"
      redirect_to [:admin, @plane]
    else
      flash[:danger] = "Sửa thất bại"
      render "edit"
    end
  end

  def destroy
    if @plane.destroy
      flash[:success] = "Xóa thành công"
      redirect_to admin_planes_path
    else
      flash[:danger] = "Xóa thất bại"
      redirect_to admin_planes_path
    end
  end

  private
  def plane_params
    params.require(:plane).permit :name, :code, :company_id
  end

  def load_plane
    @plane = Plane.find params[:id]
  end
end

app/views/admin/planes/edit.html.slim
#form-box
  h2 = t "admin.plane.edit_plane"
  hr
  = form_for [:admin, @plane] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :name
      .col-xs-6
        = f.text_field :name, class: "form-control"

    .form-group
      .col-xs-6
        = f.label :code
      .col-xs-6
        = f.text_field :code, class: "form-control"
    
    .form-group.row
      .col-xs-6
        = f.label :company_id, "Tên hãng hàng không"
      .col-xs-6
        = f.collection_select :company_id, @companies, :id, :name, {class: "form-control"}

    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.edit"), class: "btn btn-primary btn-block"

app/views/admin/planes/index.html.slim
h2 = t "admin.plane.index_plane"

table.table.table-bordered.text-center
  tr
    th.info.text-center = sort_link @search, :name, t("admin.plane.name")
    th.info.text-center = sort_link @search, :code, t("admin.plane.code")
    th.info.text-center = sort_link @search, :company_name, t("admin.plane.company")
    th.info.text-center = sort_link @search, :status, t("admin.plane.status")
    th.info.text-center = t "admin.plane.select"

  - @planes.each do |plane|
    tr
      td = plane.name
      td = plane.code
      td = plane.company.name
      td
        - if plane.not_ready?
          = link_to "Chưa sẵn sàng", admin_manage_plane_path(id: plane.id, status: "ready"), method: :patch, data: {confirm: "Phê duyệt máy bay này?"}, class: "btn btn-danger btn-xs"
        - elsif plane.ready?
          = link_to "Sẵn sàng", admin_manage_plane_path(id: plane.id, status: "not_ready"), method: :patch, data: {confirm: "Hoãn máy bay này?"}, class: "btn btn-success btn-xs"
      td
        = link_to t("button.show"), [:admin, plane] , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.edit"), edit_admin_plane_path(plane) , class: "btn btn-primary btn-xs"
        | &nbsp;&nbsp;
        = link_to t("button.delete"), [:admin, plane], method: :delete,
          data: {confirm: t("button.you_sure")}, class: "btn btn-primary btn-xs"

h4 = link_to t("admin.plane.new_plane"), new_admin_plane_path

= paginate @planes

app/views/admin/planes/new.html.slim
#form-box
  h2 = t "admin.plane.new_plane"
  hr
  = form_for [:admin, @plane] do |f|
    = render "shared/error_message", object: f.object
    .form-group.row
      .col-xs-6
        = f.label :name
      .col-xs-6
        = f.text_field :name, class: "form-control"

    .form-group.row
      .col-xs-6
        = f.label :code
      .col-xs-6
        = f.text_field :code, class: "form-control"
    
    .form-group.row
      .col-xs-6
        = f.label :company_id, "Tên hãng hàng không"
      .col-xs-6
        = f.collection_select :company_id, @companies, :id, :name, {class: "form-control"}

    .form-group.row
      .col-xs-4
      .col-xs-4
        = f.submit t("button.create"), class: "btn btn-primary btn-block"

app/views/admin/planes/show.html.slim
h2 = t "admin.plane.show_plane"

= @plane.name
= @plane.code
= @plane.company.name
= @plane.status